In [34]:
import pandas as pd
import numpy as np
import itertools
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn import metrics
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('news_dataset.csv', index_col=None)

In [3]:
df

,title,text,label
0,Foreign Democrat final.,more tax development both store agreement lawy...,real
1,To offer down resource great point.,probably guess western behind likely next inve...,fake
2,Himself church myself carry.,them identify forward present success risk sev...,fake
3,You unit its should.,phone which item yard Republican safe where po...,fake
4,Billion believe employee summer how.,wonder myself fact difficult course forget exa...,fake
...,...,...,...
19995,House party born.,hit and television I change very our happy doo...,fake
19996,Though nation people maybe price box.,fear most meet rock even sea value design stan...,real
19997,Yet exist with experience unit.,activity loss very provide eye west create wha...,real
19998,School wide itself item.,term point general common training watch respo...,fake


In [4]:
dataset=df

In [5]:
y=dataset["label"]

In [6]:
X_train, X_test, y_train, y_test = train_test_split(dataset['text'], y, test_size=0.33, random_state=53)

In [9]:
count_vectorizer=CountVectorizer(stop_words='english')  # stop_words like is,was,the,in etc will be removed
count_train=count_vectorizer.fit_transform(X_train) # fit method creates model. fit_transform creates model + predict
print(count_train)
count_test=count_vectorizer.transform(X_test) # convert the new text into the same numerical format that was already learned from the training data.

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2321047 stored elements and shape (13400, 763)>
  Coords	Values
  (0, 410)	2
  (0, 134)	1
  (0, 60)	1
  (0, 502)	2
  (0, 230)	1
  (0, 122)	1
  (0, 327)	1
  (0, 583)	1
  (0, 507)	1
  (0, 136)	1
  (0, 7)	1
  (0, 475)	1
  (0, 408)	1
  (0, 545)	1
  (0, 582)	1
  (0, 169)	1
  (0, 728)	2
  (0, 379)	1
  (0, 133)	1
  (0, 650)	1
  (0, 27)	1
  (0, 155)	1
  (0, 687)	2
  (0, 275)	1
  (0, 74)	1
  :	:
  (13399, 120)	1
  (13399, 50)	1
  (13399, 233)	1
  (13399, 220)	1
  (13399, 232)	1
  (13399, 113)	2
  (13399, 138)	1
  (13399, 524)	1
  (13399, 33)	1
  (13399, 464)	1
  (13399, 151)	1
  (13399, 299)	2
  (13399, 467)	1
  (13399, 758)	1
  (13399, 699)	1
  (13399, 748)	1
  (13399, 520)	1
  (13399, 351)	1
  (13399, 504)	1
  (13399, 715)	2
  (13399, 447)	1
  (13399, 153)	1
  (13399, 521)	1
  (13399, 694)	2
  (13399, 132)	1


In [11]:
dir(count_train)

['T',
 '__abs__',
 '__abstractmethods__',
 '__add__',
 '__array_priority__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__idiv__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__pow__',
 '__radd__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmatmul__',
 '__rmul__',
 '__round__',
 '__rsub__',
 '__rtruediv__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__slots__',
 '__static_attributes__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '_abc_impl',
 '_add_dense',
 '_add_sparse',
 '_allow_nd',
 '_argminmax',
 '_argminmax_axis',
 '_ascontainer'

In [12]:
len(count_vectorizer.get_feature_names_out())

763

In [13]:
print(count_train.toarray())

[[1 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]]


In [14]:
# So far we have created the vectors for train and test dataset which are now available as numbers. Now we are going to create the model using
# multinomialnb.

# MULTINOMIALNB

In [18]:
clf=MultinomialNB()
clf.fit(count_train, y_train)
pred=clf.predict(count_test)
score=metrics.accuracy_score(y_test, pred)
print("accuracy: %0.3f" %score)

cm=metrics.confusion_matrix(y_test, pred, labels=['fake','real'])

accuracy: 0.507


In [19]:
from sklearn.metrics import classification_report
report=classification_report(y_test,pred)

In [21]:
print(report)

              precision    recall  f1-score   support

        fake       0.51      0.52      0.52      3329
        real       0.50      0.49      0.50      3271

    accuracy                           0.51      6600
   macro avg       0.51      0.51      0.51      6600
weighted avg       0.51      0.51      0.51      6600



# Logistic Regression

In [24]:
clf_1=LogisticRegression(max_iter=1000,random_state=0)
clf_1.fit(count_train, y_train)
pred=clf_1.predict(count_test)
score=metrics.accuracy_score(y_test, pred)
print("accuracy: %0.3f" %score)

cm=metrics.confusion_matrix(y_test, pred, labels=['fake','real'])

accuracy: 0.511


# PassiveAggressiveClassifier

In [26]:
clf_2=PassiveAggressiveClassifier()
clf_2.fit(count_train, y_train)
pred=clf_2.predict(count_test)
score=metrics.accuracy_score(y_test, pred)
print("accuracy: %0.3f" %score)

cm=metrics.confusion_matrix(y_test, pred, labels=['fake','real'])

accuracy: 0.500


# RandomForest

In [30]:
clf_3=RandomForestClassifier(n_estimators=10, criterion='entropy', random_state=0)
clf_3.fit(count_train, y_train)
pred=clf_3.predict(count_test)
score=metrics.accuracy_score(y_test, pred)
print("accuracy: %0.3f" %score)

cm=metrics.confusion_matrix(y_test, pred, labels=['fake','real'])

accuracy: 0.499


# Decision Tree

In [32]:
clf_4=DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
clf_4.fit(count_train, y_train)
pred=clf_4.predict(count_test)
score=metrics.accuracy_score(y_test, pred)
print("accuracy: %0.3f" %score)

cm=metrics.confusion_matrix(y_test, pred, labels=['fake','real'])

accuracy: 0.500


# SVM

In [35]:
clf_5=SVC(kernel = 'rbf', random_state = 0)
clf_5.fit(count_train, y_train)
pred=clf_5.predict(count_test)
score=metrics.accuracy_score(y_test, pred)
print("accuracy: %0.3f" %score)

cm=metrics.confusion_matrix(y_test, pred, labels=['fake','real'])

accuracy: 0.512


# Predicting first row 

In [36]:
dataset["text"][0]

'more tax development both store agreement lawyer hear outside continue reach difference yeah figure your power fear identify there protect security great national nothing fast story why late nearly bit cost tough since question to power almost future young conference behind ahead building teach million box receive Mrs risk benefit month compare environment class imagine you vote community reason set once idea him answer many how purpose deep training game own true language garden of partner result face military discover discover data glass bed maintain test way development across top culture glass yes decision hope necessary as trade organization talk debate peace stay community development six wide write itself several fight teach billion for common fear we personal church establish store kind hundred debate hotel cut sister audience sound case that stay within information trouble be debate great themselves responsibility force people hundred bar miss others sometimes build room inte

In [37]:
count_train[[0]]

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 146 stored elements and shape (1, 763)>

In [39]:
X_train[[0]]

0    more tax development both store agreement lawy...
Name: text, dtype: object

In [40]:
clf.predict(count_train[[0]])

array(['real'], dtype='<U4')